### ISSUE TITLE
Please add description to *.list files in README.md

### ISSUE THREAD

**Issue by mschabhuettl** [slyfox1186/pihole.youtube.blocklist#1]
Hello!

Stumbled on this project via reddit. Very interesting! Had some bad luck with youtube ad blocking via Pi-hole in the past (overblocking - video not starting cause ad and video is located on same server). Haven't tested your lists yet, but I'm looking forward to.

Could you please provide a description in README.md for each list to see what it's ment for?

Cheers!

**Comment by slyfox1186** [comment]
This is done. Thanks.
