### ISSUE TITLE
Blocking YouTube or Twitch Ads

### ISSUE THREAD

**Issue by attheshow2** [slyfox1186/pihole.youtube.blocklist#10]
I'm just curious, do the filters in this project currently help with blocking ads on either Twitch or YouTube? Those are 2 big services I'm wondering if someone already has a technique for. I've heard that blocking YouTube is currently not possible since they serve from the same servers as the videos, but maybe you've found a regex that works? Thanks!

**Comment by slyfox1186** [comment]
I have a lot of experience in trying to block youtube. Currently, the way they rotate their domains and their naming schemes make it impossible unless you have the key that breaks their code. It's just too random. A domain that servers an ad today could be "switched" the next hour to serve the actual video and back and forth and then there are a million other domain possibilities past that. So no YouTube is not blockable by pihole. Your absolute best bet is a browser extension for blocking ads. Try the big-name ones. I think one or more of them actually does a pretty decent job.

Twitch I have not looked into. I will do so.
