### ISSUE TITLE
Pihole RegEx and Exact Lists: Script error

### ISSUE THREAD

**Issue by HuckToohey** [slyfox1186/pihole.youtube.blocklist#12]
`run.sh: line 20: Script error: The shell scripts were not found.: command not found`

When I download the page contents manually and then run ./run.sh locally I get:
`./run.sh: 65: Syntax error: "(" unexpected`

**Comment by HuckToohey** [comment]
Oops, so sorry -- forgot to run as su.

**Comment by HuckToohey** [comment]
Oh, crap, the error is with the regexp/block script which is in fact broken and I closed the issue prematurely. The Adlist script is working as expected.

**Comment by slyfox1186** [comment]
I'll be back at my PC this evening. I'll figure out what is wrong. Thanks for the update.

**Comment by slyfox1186** [comment]
OK this should be fixed. Thanks again for alerting me.

Cheers. J
