### ISSUE TITLE
Most of the regular expressions in this project don't work for pihole

### ISSUE THREAD

**Issue by BenjaminAm** [slyfox1186/pihole.youtube.blocklist#4]
The Pihole REGEX implementation doesn't suport some of the expressions you used in the youtube regex blocklist as stated here https://docs.pi-hole.net/regex/tutorial/

Especially your expressions in brackets use the common regex syntax but pihole has some different syntax there. This results in the targeted domains not being matched. You can use the command found here https://docs.pi-hole.net/regex/testmode/ to test domains against the active set of expressions.. 

My updated versions of your regex':
Displaying regex blacklist:
  1: ^[\w\-\.]*?google(?:adservices|apis|syndication|usercontent)?\.com$ (disabled, last modified Tue, 09 Nov 2021 14:25:27 +0100)
  2: ^[\w\-\.]*?l\.google\.com$ (disabled, last modified Tue, 09 Nov 2021 14:25:43 +0100)
  3: ^clients\d+?\.google\.com$ (disabled, last modified Tue, 09 Nov 2021 14:25:46 +0100)
  4: ^r[-0-9]+sn[-.a-zA-Z0-9]+googlevideo\.com (enabled, last modified Tue, 09 Nov 2021 17:24:57 +0100)
  5: ^r[.0-9]+sn.*googlevideo\.com$ (enabled, last modified Tue, 09 Nov 2021 17:27:59 +0100)
  6: ^[-.0-9a-zA-Z]*double(?:lick|click)\.net$ (enabled, last modified Tue, 09 Nov 2021 17:29:47 +0100)
  7: ^[-.0-9a-zA-Z]*?manifest\.googlevideo\.com$ (enabled, last modified Tue, 09 Nov 2021 19:36:57 +0100)
  8: ^beacons\.gv[-.0-9a-zA-Z]+\.com$ (enabled, last modified Tue, 09 Nov 2021 19:41:19 +0100)
  9: ^clients[0-9]+\.youtube\.com$ (enabled, last modified Tue, 09 Nov 2021 20:53:06 +0100)

1-3 are unchanged from your list but disabled, since I didn't see any use for blocking youtube ads so far. #1 even blocked google.com which obviously isn't desired.

I hope this is helpful to you 👍

**Comment by Lilleri** [comment]
confirm the regex listed does not work for me either, installed fresh pihole just yesterday
