### ISSUE TITLE
Wrong regexes in youtube-regex-filters.txt

### ISSUE THREAD

**Issue by dmbsg** [slyfox1186/pihole.youtube.blocklist#5]
Hi there,

Pi-Hole v5.7 is unable to use the following regexes:
^[\w-.]?google(?:adservices|apis|syndication|usercontent)?\.com$ 
^[\w-.]?l\.google\.com$ 

The error message is - Invalid character range.
Could you fix them please?

**Comment by hellotinh03** [comment]
Same problem here

**Comment by asolopovas** [comment]
+1

**Comment by slyfox1186** [comment]
I have redone a lot of my regex filters so they should work much better. Thanks for alerting me.
