### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by thespica93** [slyfox1186/pihole.youtube.blocklist#7]
Hello,

I run all 4 scripts however, it seems to block to much. All profile pictures and posts on Facebook become blocked

How can I resolve this?
Thank you

**Comment by slyfox1186** [comment]
I have removed one of the entries `(\.|^)facebook(|corewwwi)\.(com|onion|net)$`

Lets see how that affects things. Thank you for bringing this to my attention. If things don't improve I will remove another entry.
